### ISSUE TITLE
博客部署错误

### ISSUE THREAD

**Issue by meringueclouds** [shw2018/hexo-blog-fly#12]
生成页面和本地预览都一切正常，在部署时，出现以下错误：

```bash
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (node:fs:2791:10)
    at tryCatcher (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\程训庚\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at D:\棉花糖云海の知识树\node_modules\hexo-fs\lib\fs.js:144:39
    at tryCatcher (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\棉花糖云海の知识树\node_modules\bluebird\js\release\promise.js:643:18)
```

麻烦大佬想想解决办法，谢谢♪(･ω･)ﾉ

**Comment by shw2018** [comment]
node用低版本
