### ISSUE TITLE
大佬,部署了几个小时了一直失败

### ISSUE THREAD

**Issue by boomwb** [shw2018/hexo-blog-fly#13]
$ hexo d
ERROR Plugin load failed: hexo-filter-github-emojis
Error: Cannot find module 'ip-regex'
Require stack:
- E:\Git_Projecr\boomwb.github.io\node_modules\tough-cookie\lib\cookie.js
- E:\Git_Projecr\boomwb.github.io\node_modules\jsdom\lib\api.js
- E:\Git_Projecr\boomwb.github.io\node_modules\hexo-filter-github-emojis\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (E:\Git_Projecr\boomwb.github.io\node_modules\tough-cookie\lib\cookie.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (E:\Git_Projecr\boomwb.github.io\node_modules\jsdom\lib\api.js:5:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (E:\Git_Projecr\boomwb.github.io\node_modules\hexo\lib\hexo\index.js:219:21)
    at E:\Git_Projecr\boomwb.github.io\node_modules\hexo-filter-github-emojis\index.js:7:19
    at E:\Git_Projecr\boomwb.github.io\node_modules\hexo\lib\hexo\index.js:232:12
    at tryCatcher (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:517:31)
ERROR Plugin load failed: hexo-lazyload-image
Error: EISDIR: illegal operation on a directory, read
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be of type number. Received an instance of Object
    at copyFile (node:fs:2943:10)
    at tryCatcher (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\dell\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at E:\Git_Projecr\boomwb.github.io\node_modules\hexo-fs\lib\fs.js:144:39
    at tryCatcher (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\Git_Projecr\boomwb.github.io\node_modules\bluebird\js\release\promise.js:643:18)

**Comment by boomwb** [comment]
解决了
