### ISSUE TITLE
大佬，我clone后，就想看看没修改配置前的效果，hexo g和hexo s后，提示

### ISSUE THREAD

**Issue by melodyjerry** [shw2018/hexo-blog-fly#4]

**Comment by melodyjerry** [comment]
Unhandled rejection TypeError: G:\blog\themes\hexo-blog-fly\layout\index.ejs:3
    1| 
    2| <% if (is_home() && page.current === 1) { %>
 >> 3| <%- partial('_partial/index-cover') %>
    4| <% } else { %>
    5| <%- partial('_partial/bg-cover') %>
    6| <% } %>

G:\blog\themes\hexo-blog-fly\layout\_partial\index-cover.ejs:72
    70|                 </a>
    71|
 >> 72|                 <% if (theme.indexbtn && theme.indexbtn.enable) { %>
    73|                 <a href="<%- theme.indexbtn.url %>" class="waves-effect waves-light btn" target="_blank">
    74|                     <i class="fa <%- theme.indexbtn.icon %>"></i><%- theme.indexbtn.name %>
    75|                 </a>

Cannot read property 'enable' of undefined
    at eval (eval at compile (G:\blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:47:36)
    at returnedFn (G:\blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync (G:\blog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (G:\blog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (G:\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (G:\blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:14:17)
    at returnedFn (G:\blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled (G:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (G:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at G:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by melodyjerry** [comment]
@shw2018 这个是怎么回事？是我clone的不完整吗？

你试一下把node_modules文件夹删掉，下载文件保持源文件不变，npm i 安装依赖包。

**Comment by iTomstudio** [comment]
我也是同样是问题，请问解决了吗？
